"""Add multiple media support and category-specific fields to projects

Revision ID: d94b4ee29ff1
Revises: de647880292a
Create Date: 2026-04-15 23:16:03.648576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94b4ee29ff1'
down_revision = 'de647880292a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('videos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('web_dev_stack', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graphic_design_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('graphic_design_tools', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_editing_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_editing_software', sa.Text(), nullable=True))

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('video_editing_software')
        batch_op.drop_column('video_editing_type')
        batch_op.drop_column('graphic_design_tools')
        batch_op.drop_column('graphic_design_type')
        batch_op.drop_column('web_dev_stack')
        batch_op.drop_column('videos')
        batch_op.drop_column('images')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
