"""Add project_type and software_used fields to Project model

Revision ID: de647880292a
Revises: 7d6cac1ec7e7
Create Date: 2026-04-15 22:52:48.469113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de647880292a'
down_revision = '7d6cac1ec7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('software_used', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('software_used')
        batch_op.drop_column('project_type')

    # ### end Alembic commands ###
